"""
CLI for ADK agents generated by agent_forge.

Reads ROOT_AGENT and SUB_AGENTS from tools.config (from .env), dynamically
imports root_agent and sub-agents via importlib, and runs the app.

Accepts user query with debug and thoughts options.

Usage:
python -m main run --help

"""

from __future__ import annotations

import asyncio
import importlib
import os
import sys

import click

from google.adk.apps.app import App
from google.adk.planners.built_in_planner import BuiltInPlanner
from google.genai import types

from tools.config import AI_MODEL_NAME, INCLUDE_THOUGHTS, LOCAL_LLM, ROOT_AGENT, SUB_AGENTS
from tools.logging_utils import setup_logging, THEME
from tools.runner_utils import execute_agent_stream, APP_NAME


def _load_root_agent() -> object:
    mod = importlib.import_module(f"{ROOT_AGENT}.agent")
    root = getattr(mod, "root_agent", None)
    if root is None:
        raise SystemExit(f"root_agent not found in {ROOT_AGENT}.agent")
    return root


def _load_sub_agent(name: str) -> object:
    mod = importlib.import_module(f"{ROOT_AGENT}.sub_agents.{name}.agent")
    agent = getattr(mod, name, None)
    if agent is None:
        raise SystemExit(f"Sub-agent {name!r} not found in {ROOT_AGENT}.sub_agents.{name}.agent")
    return agent


def _load_agents() -> tuple[object, list[object]]:
    root = _load_root_agent()
    subs = [_load_sub_agent(name) for name in SUB_AGENTS]
    return root, subs


@click.group(context_settings={"help_option_names": ["-h", "--help"]})
def cli() -> None:
    """CLI for ADK Agents (config-driven)."""
    pass


@cli.command("run")
@click.option(
    "--input", "-i",
    "input_text",
    help="Input text for the agent. If omitted, read from stdin.",
)
@click.option(
    "--debug", "-d",
    "debug",
    is_flag=True,
    default=False,
    help="Enable event tracing and state inspection.",
)
@click.option(
    "--thoughts", "-t", "show_thoughts",
    is_flag=True,
    default=False,
    help="Show agent's inner reasoning.",
)
def run_command(
    input_text: str | None,
    debug: bool,
    show_thoughts: bool,
) -> None:
    """Run the project's dedicated agent."""
    include_thoughts = show_thoughts or (debug and INCLUDE_THOUGHTS)
    root_agent, sub_agents = _load_agents()
    agents_to_update = [root_agent] + sub_agents

    for agent in agents_to_update:
        if getattr(agent, "planner", None) and isinstance(agent.planner, BuiltInPlanner):
            agent.planner.thinking_config = types.ThinkingConfig(include_thoughts=include_thoughts)

    setup_logging(debug=debug, model_name=AI_MODEL_NAME)

    if input_text is None:
        if not sys.stdin.isatty():
            input_text = sys.stdin.read().strip()
        else:
            click.secho("Error: No input provided. Use --input or pipe text.", **THEME["err"])
            return

    app = App(name=APP_NAME, root_agent=root_agent)
    initial_state = {
        "root_agent": ROOT_AGENT,
        "sub_agent": SUB_AGENTS,
        "application": APP_NAME,
        "environment": os.getenv("AGENT_ENV", "development"),
        "model_name": AI_MODEL_NAME,
        "local_llm": LOCAL_LLM,
        "include_thoughts": include_thoughts,
    }

    try:
        final_text = asyncio.run(
            execute_agent_stream(app, input_text, initial_state, debug)
        )
        click.echo(f"\n{final_text}")
    except ValueError as ve:
        click.secho(f"\n[Validation Error]: {ve}", **THEME["err"])
        sys.exit(1)
    except Exception as e:
        click.secho(f"\n[System Failure]: {e}", **THEME["err"])
        if debug:
            import traceback
            traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    cli()
